# Generated by Django 3.0.6 on 2020-05-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='address',
            new_name='street',
        ),
        migrations.AlterField(
            model_name='organization',
            name='logoimage',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
